# Schema for the configuration files of the log module.
log.type.*:
  type: config_entity
  label: 'Log type'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Type'
    description:
      type: text
      label: 'Description'
    name_pattern:
      type: string
      label: 'Pattern for auto-generating the log name, using tokens.'
    workflow:
      type: string
      label: 'Workflow'

condition.plugin.log_type:
  type: condition.plugin
  mapping:
    bundles:
      type: sequence
      sequence:
        type: string

action.configuration.log_done_action:
  type: action_configuration_default
  label: 'Mark log as done configuration'
